# -*- coding: utf-8 -*-
"""image similarity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LRAm6-J1MJzRNyONwvAooyuirlwQ4nL-
"""

from PIL import Image
import numpy as np

pic1 = Image.open('/content/person (4).jpg')
pic2 = Image.open('/content/person (5).jpg')

pic1_reshape = pic1.resize((round(pic1.size[0]*0.5), round(pic1.size[1]*0.5)))
pic2_reshape = pic2.resize((round(pic1.size[0]*0.5), round(pic1.size[1]*0.5)))

pic_array1 = np.array(pic1_reshape)
pic_array2 = np.array(pic2_reshape)

pic_array1 = pic_array1.flatten()
pic_array2 = pic_array2.flatten()

pic_array1 = pic_array1/255
pic_array2 = pic_array2/255

from scipy import spatial

similarity = -1 * (spatial.distance.cosine(pic_array1, pic_array2) - 1)

similarity

img = Image.open('/content/person (8).jpg')
img_reshape = img.resize((round(pic1.size[0]*0.5), round(pic1.size[1]*0.5)))
img_array = np.array(img_reshape)
img_array = img_array.flatten()
img_array = img_array/255

similarities = -1 * (spatial.distance.cosine(pic_array2, img_array) - 1)

similarities

